### ISSUE TITLE
Todo List Management

### ISSUE THREAD

**Issue by sdq11111** [CyberZHG/CrimsonTomato#1]
* Add and delete todo
* Start timer from todo, the title will be the task name
* Ask if todo is finished
* Sort by priority/datetime
* Task period counter
* Task color

**Comment by sdq11111** [comment]
![1 0 5_1](https://cloud.githubusercontent.com/assets/4705089/8390655/6c1cf578-1cd3-11e5-89ff-ad5e0923dd31.jpg)
![1 0 5_2](https://cloud.githubusercontent.com/assets/4705089/8390659/6c709ed0-1cd3-11e5-9c24-de8cebc21f09.jpg)
![1 0 5_3](https://cloud.githubusercontent.com/assets/4705089/8390658/6c6cd318-1cd3-11e5-89ac-87bf3b1481ea.jpg)
![1 0 5_4](https://cloud.githubusercontent.com/assets/4705089/8390656/6c4a6760-1cd3-11e5-9207-69bfebd450c4.jpg)
![1 0 5_5](https://cloud.githubusercontent.com/assets/4705089/8390657/6c6b8292-1cd3-11e5-924f-a0e751aa8b00.jpg)

**Comment by CyberZHG** [comment]
![1.0.6_1](https://cloud.githubusercontent.com/assets/853842/8395453/ee316f6e-1da3-11e5-94a6-9755d27357fd.jpg)
![1.0.6_2](https://cloud.githubusercontent.com/assets/853842/8395451/ee2fb052-1da3-11e5-8cff-3751e501e885.jpg)
![1.0.6_3](https://cloud.githubusercontent.com/assets/853842/8395452/ee313080-1da3-11e5-861f-a60e6b36a8ff.jpg)

**Comment by CyberZHG** [comment]
![1](https://cloud.githubusercontent.com/assets/853842/11316782/2e67beb6-9050-11e5-880c-6133029eaf12.png)
![2](https://cloud.githubusercontent.com/assets/853842/11316779/26c1690a-9050-11e5-9fcd-9cd7f25e93f8.png)
![3](https://cloud.githubusercontent.com/assets/853842/11316781/26c6961e-9050-11e5-8b74-e702ae47e6d7.png)

**Comment by CyberZHG** [comment]
![1](https://cloud.githubusercontent.com/assets/853842/11317338/cf4ff8f0-9066-11e5-9be3-87cffcedf80f.png)
![2](https://cloud.githubusercontent.com/assets/853842/11317339/cf502460-9066-11e5-94a9-71a87020643a.png)
![3](https://cloud.githubusercontent.com/assets/853842/11317340/cf51cd1a-9066-11e5-9759-92de1fd265a7.png)
